# https://git-cliff.org/docs/

[bump]
initial_tag = "v0.0.1"

[remote.github]
owner = "wodore"
repo = "wodore-frontend-quasar"
token = "${GITHUB_TOKEN}"

[git]
tag_pattern = "^v[0-9]+\\.[0-9]+\\.[0-9]+"
sort_commits = "newest"
conventional_commits = false
filter_unconventional = false
#topo_order = true
commit_parsers = [
  { field = "github.pr_labels", pattern = "INTERNAL", skip = true },
  { field = "github.pr_labels", pattern = "BREAKING", group = "<!-- 00 -->ğŸš§ Breaking changes" },
  { field = "github.pr_labels", pattern = "type:feature", group = "<!-- 10 -->ğŸš€ Features" },
  { field = "github.pr_labels", pattern = "type:bug", group = "<!-- 20 -->ğŸ› Fixes" },
  { field = "github.pr_labels", pattern = "type:refactor", group = "<!-- 30 -->ğŸ“ Refactor" },
  { field = "github.pr_labels", pattern = "type:docs", group = "<!-- 40 -->ğŸ“˜ Documentation" },
  { field = "github.pr_labels", pattern = "type:deps", group = "<!-- 50 -->ğŸ“¥ Dependencies" },
  { field = "github.pr_labels", pattern = "type:tooling", group = "<!-- 60 -->ğŸ’» Tooling" },
  { field = "github.pr_labels", pattern = "type:tests", group = "<!-- 70 -->ğŸ©º Tests" },
  { field = "github.pr_labels", pattern = "type:others", group = "<!-- 80 -->ğŸˆ Others" },
  { field = "github.pr_labels", pattern = ".*", skip = true },
]

# remove last added merged requests, they are added below again (with url).
commit_preprocessors = [{ pattern = '\.?\s*\(#[0-9]+\)$', replace = "" }]

[changelog]
# template for the changelog header
# https://keats.github.io/tera/docs/#introduction
header = """
<!-- Auto generated. Run 'inv release' in order to update -->\n
# Changelog\n
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}
{% for group, commits in commits | group_by(attribute="group") %} {# Messages #}
    #### {{ group | striptags | trim | upper_first }}
    {%- for commit in commits %}
        - {{ commit.remote.pr_title | split(pat="\n") | first | upper_first | trim }}\
            {% if commit.remote.pr_number %}\
            {# #} ([#{{ commit.remote.pr_number }}]) \
            {%- endif -%}
            {# #} - [{{ commit.id | truncate(length=7, end="") }}]\
    {% endfor %}
{% endfor %}
{% for group, commits in commits | group_by(attribute="group") %}{# Links (PR and commits) #}
    {%- for commit in commits %}
            {% if commit.remote.pr_number %}\
            {# #}[#{{ commit.remote.pr_number }}]: {{ self::remote_url() }}/pull/{{ commit.remote.pr_number }} \
            {%- endif -%}
            {# #}\n[{{ commit.id | truncate(length=7, end="") }}]: {{self::remote_url() }}/commit/{{ commit.id }} \
    {% endfor %}
{% endfor %}
{% if version -%}
    {% if previous -%}
        [{{ version | trim_start_matches(pat="v") }}]: \
            {{ self::remote_url() }}/compare/{{ previous.version }}..{{ version }} \
    {% else -%}
        [{{ version | trim_start_matches(pat="v") }}]: \
            {{ self::remote_url() }}/releases/tag/{{ version }} \
    {% endif -%}
{% else -%}
    {% if previous -%}
        [unreleased]: {{ self::remote_url() }}/compare/{{ previous.version }}..HEAD
    {% endif -%}
{% endif -%}
{# #}\n
"""
footer = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""
# remove the leading and trailing whitespace from the templates
trim = true
